### ISSUE TITLE
tracking check marks 

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#101]
I went through all of S1, but not all of my boxes are checked off. Maybe because videos aren't in yet? 
See attached. 
![tracking](https://cloud.githubusercontent.com/assets/19825728/16025377/f7faa0c8-3194-11e6-8e8a-3b39eb20ed4e.jpg)

**Comment by castl350** [comment]
It's not the video, but the CYK questions for these activities are missing currently. so, we'll either add them in or request some be written..otherwise the setting for completion has to go to "viewed" instead of "graded"

**Comment by mattsema** [comment]
confirmed all activity completion settings
**lessons**:
require grade if interactive question is present
require view if no interactive question is present
**questionnaire**: require submission
**quiz**: require grade
**discussion**: require reply
