### ISSUE TITLE
Periods after objectives

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#108]
It looks like sometimes there are periods and sometimes not ... this is inconsistent from lesson to lesson and also within a list of lesson objectives

Is this a big deal and something we want to systematically go in and address or not? Not sure where it stands in the big scheme of things - Bev? Brittany?

**Comment by castl350** [comment]
The rules are that objectives should have periods if the header and the objective make a complete sentence. So, for example: 

In this session you should:
- Learn about PC.
- See what PC looks like.

Otherwise, they don't get periods...hope that helps

**Comment by castl350** [comment]
Example..on this page the list of indicators should not have a period....the objective below do..and i noticed they have periods pretty consistently throughout the course. If you find discrepancies, you'll have to report specific pages.
![screen shot 2016-07-22 at 11 05 39 am](https://cloud.githubusercontent.com/assets/3357288/17061407/5e9ac9c2-4ffc-11e6-9ec6-b21f96b4b330.png)
