### ISSUE TITLE
S3 PC All About Interactive Qu after Part 5 of 5 

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#111]
I must have missed drafting one of these - my apologies! How is this one?

Which one of these scenarios shows Promoting Positive Peer Interactions?

The teacher says, "Give me a high five. You threw that away by yourself." 
The teacher says, "Way to go. You two are both sharing the blocks so well now."
The teacher says, "Great job picking out a book for us to read today."

Feedback for correct: That's right! While all of these scenarios are signs of Positive Climate, this example highlights Promoting Positive Peer Interactions because the teacher acknowledges the children's efforts to share.

Feedback for incorrect: Remember, Promoting Positive Peer Interactions is about teachers who intentionally encourage peer connections, model social skills, and acknowledge social behavior."

**Comment by castl350** [comment]
i added it in. I did not include the feedback for incorrect, because we have consistently left that blank in this course. The learner simply gets an "incorrect. please try again message."

**Comment by castl350** [comment]
Note feedback
![screen shot 2016-07-22 at 11 11 12 am](https://cloud.githubusercontent.com/assets/3357288/17061551/11a378d4-4ffd-11e6-8680-589ea9ce0ecb.png)
![screen shot 2016-07-22 at 11 11 25 am](https://cloud.githubusercontent.com/assets/3357288/17061553/12797ff6-4ffd-11e6-90f5-da97dad42a4c.png)
