### ISSUE TITLE
S3 A3 WILL Part 1 of 5 video

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#112]
I know that we're not supposed to report issues re: the video but for the Part 1 video at 0024 the indicators across the top read:
Connect with Children
Communicate Positively 
Show Respect 
Support Children's Independence - this isn't right - change to Promote Positive Peer Interactions

This is correct in the video for Part 3
THANK YOU!

**Comment by castl350** [comment]
Sarah, I'll leave this once for you since it's video related.

**Comment by sarahlydic** [comment]
Corrected video and put on on server
