### ISSUE TITLE
S3 A3 WILL part numbers need adjusting, missing video, unclear directions, indicator chart is missing 4th indicator

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#113]
The 'Continue' button at the bottom of Part 3 of 5: What We Saw links to 

Part 5 of 6: Record What You See

Video is missing 

Unclear directions, consider revising to:
Describe Your Observations instead of Record What You See
2nd bullet - Describe the behaviors you see related to Positive Climate.

**Comment by castl350** [comment]
Hi guys. Kathy Here. I fixed the continue button. I also added in the PEER Indicator missing in the chart alongside the video. Matt and Sarah, please make sure the video for the interactive piece in part 4 of 5 is added in and working.

Allison, i noticed that the feedback for the comparison page is missing? Not sure if we missed this content or if it has not been written? I'll check the other issues to see if it's something that was noted in a separate ticket.

**Comment by castl350** [comment]
![screen shot 2016-07-22 at 11 18 14 am](https://cloud.githubusercontent.com/assets/3357288/17061800/50339970-4ffe-11e6-9d4d-a60cbdfa578e.png)

**Comment by castl350** [comment]
![screen shot 2016-07-22 at 11 18 27 am](https://cloud.githubusercontent.com/assets/3357288/17061813/59497a52-4ffe-11e6-8317-3f64330c4619.png)

**Comment by castl350** [comment]
PS I am leaving the directions as on this page. They were used in the previous toddler pilots exactly the same way, and learners did not report an issue of confusion, so we will leave the consistent across all the WILLs.

**Comment by sarahlydic** [comment]
all videos on server. feedback written
