### ISSUE TITLE
S3 A3 WILL needs some work - text, videos, ordering 

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#114]
Compare your answer to ours: 

APL not sure what feedback to draft here b/c I am not sure which video it is - Sarah/Kathy - let's talk about this one ... 

And then there is incorrect so then I am stuck in a loop I can't get out of

**Comment by mattsema** [comment]
addressed incorrect answer by adding score of 1

**Comment by sarahlydic** [comment]
all videos on server. feedback written
