### ISSUE TITLE
S3 A4 Let's Observe and Discuss Together

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#115]
I know that we can't continue to the next lesson from this page ... but I am wondering is there any way to get rid of all that you can do related to posting, like the subscription, attachment, mail now, group business. I think we just want a text box for learners and that's it?

And at first I couldn't figure out where to reply to as there are two places.

So for MY post I click on Reply bottom right hand corner of video but what is more obvious is clicking reply to other posts ... this is quite possibly an Allison thing as I don't participate in any social media or discussion boards ... so maybe this is super obvious to others

**Comment by castl350** [comment]
Forum functinalities are built into the lms and can not be changed without major overhaul to all courses and sections.

**Comment by castl350** [comment]
Kathy here...this is built into the LMS as standard functionality for the discussion board, and learners did not report problems using it in the previous pilots. I agree it would be cleaner to have an interface with just a box, but that this LMS and interface does not have that option. That is more of a CANVAS clean functionality. Hope that helps.
