### ISSUE TITLE
S3 A5 How PC Interactions Support Children's Development 

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#116]
Missing image on intro page

Missing video

**Comment by castl350** [comment]
I added image on video page. Sarah or Matt, please work together to confirm whether this lesson needs to pull the CD lesson from Pilot 2 (not sure there were changes on this lesson?) or whether Sarah is working on a new one to put here.

**Comment by sarahlydic** [comment]
JLC is recording audio for one sentence for this file (to account for the new PC indicator). Will email Matt to put the file in in once this sentence is added.

**Comment by sarahlydic** [comment]
Video has been added to LMS.
