### ISSUE TITLE
s3 A6 Intentionally Building PC - interactive question

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#118]
QUESTION after PART 2
Feedback for the correct answer 

- add exclamation point after That's Right - we've been doing that pretty consistently
- uncapitalize the words little respect

Also ALL of the answers are registered as incorrect so I am stuck in the question when really the right answer is, "A teacher picks up a child without warning him first and moves him from one center to the next."

QUESTION AFTER PART 3
Feedback for the correct answer 

- add exclamation point after That's Right - we've been doing that pretty consistently

Also this registers as incorrect so I am also stuck in this question and can't move through lesson

**Comment by mattsema** [comment]
all issues addressed
