### ISSUE TITLE
S3 Discussion

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#121]
Maybe it is just my view/access when it comes to forums but it'd be great if learners could just post to text box and not have the other options like attachments, etc.

**Comment by castl350** [comment]
this is function of the LMS in moodle and can't be changed. It was like this in both of the previous pilots as well and learners did fine. We also don't think it looks particularly nice and fluid, but it's feature that we can't change...other LMSs like Canvas do a better job of this.
