### ISSUE TITLE
S4 A2 All About CYK after Part 3

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#132]
Please revise as follows.

End second sentence after the word emotions. Start new sentence: The teacher in this example makes an effort to help the child solve a problem he is facing, and by the end of the interaction, (keep the rest)

**Comment by castl350** [comment]
I did not revise this because it did not seem to make sense with the question and the feedback? The directions here to keep the rest and add that in did not make sense. Perhaps we have the wrong question listed here (part 3)?
