### ISSUE TITLE
S4 A3 WILL TS - all of it needs reworking

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#134]
The video for PC is in here instead of the video for TS and all of the lesson is for PC which the PC also needed reworking ... Sarah/Kathy happy to sit with you all and work through this - APL

**Comment by castl350** [comment]
Sarah, these were your responsibilities. Can you set this up as needed and works with APL. Thank you. I will get the flow set up and the information in correctly for now so that the main things left are the videos and feedback.

**Comment by castl350** [comment]
Okay, all flow is set up. I'm emailing Matt separately to address the looping issue on the part 4 of 5. Videos and feedback are all that is missing now. Instructions have been updated on part 4 of 5 to match PC. Please do not change.

**Comment by castl350** [comment]
![screen shot 2016-07-22 at 12 24 06 pm](https://cloud.githubusercontent.com/assets/3357288/17063897/a596d4d2-5007-11e6-92fd-a4cb97488363.png)
