### ISSUE TITLE
S4 A8 Intentionally Promotig Emotion Regulation interactive qu after Part 1

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#141]
2 of the items are the wrong items for this question. Take out:
After a negative consequence ... 
Follow through is critical ...

Replace with:
Songs and books provide fun and engaging opportunities to introduce and label emotions.

Physical techniques are ways children can relax their bodies when they are experiencing strong emotions.

Also for the correct feedback put in an exclamation mark after the That's right

**Comment by castl350** [comment]
fixed. I also took out the option, there are several strategies teachers can use? This felt really vague to me after reading the other options.
