### ISSUE TITLE
S4 TYK Questions

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#145]
Qu 3 item C should read: "...the teacher gives the children materials to ..." and add an 's' to the word greet

Qu 4 item A should be makes instead of making

Qu 5 - Bev/Brittany I seriously got this one wrong ... should we consider changing? Or am I just an idiot?

**Comment by mattsema** [comment]
revised question 4
question 3 - added s to greet - other part should read as child?

**Comment by sarahlydic** [comment]
@ajp9e @bnkerr @bds2p 
here's a question about the TYKs :)

**Comment by ajp9e** [comment]
This question is fine. Allison might be an idiot :)
