### ISSUE TITLE
S4 Practice Applying What You've Learned intro page

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#146]
3rd sentence first word should be: Your

**Comment by castl350** [comment]
fixed this and updated instruction to exclude the coaching and technology tab

**Comment by castl350** [comment]
update: i finally realized the coaching/technology tab was related to the binder teachers get. can't use the word tab in an online setting without thinking of the navigation, so i updated the directions to be more appropriate and reference the printed materials.
