### ISSUE TITLE
S4 Practice Applying What You've Learned quiz tool questions

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#147]
Info box after Qu #1 and after Qu #7 
2nd sentence revise to: .... consider what you can do to practice ...
Put the word 'will' between interactions and impact

Info box after Qu #4 - Put the word 'will' between interactions and impact

Once quiz is submitted for all of the dropdown questions please hide the feedback function - there should not be feedback for these

Also when you review this is says 
YOUR FINAL GRADE FOR THIS QUIZ IS 0.00/0.00 is there any way to get rid of that? If so please remove in all of these - thanks

**Comment by mattsema** [comment]
questions revised
feedback hidden
can not hide final grade (this would impact all quiz tool items including graded tyks)
