### ISSUE TITLE
S5 A2 All About Regard for Child Perspectives

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#149]
Part 1:
The CASTL logo gets cut off slightly in the video before enter fullscreen mode and then much more after entering fullscreen. (seems to happen throughout) 
![1](https://cloud.githubusercontent.com/assets/19825728/16862702/0a414352-4a1a-11e6-86dc-873b03eef50c.jpg)
Part 3:
There is some link (starts with inner I think) that flashes for a few seconds before going to the video of Allison. It is pretty quick to pass (at least on my internet), so I wasn't able to get a screenshot. (seems to happen on some others as well) 
Part 4:
This is how the video starts. 
![2](https://cloud.githubusercontent.com/assets/19825728/16862846/4aa3a61e-4a1b-11e6-9078-a342bb560ec0.jpg)
Part 5:
Big gap between video box and continue button.
![3](https://cloud.githubusercontent.com/assets/19825728/16862917/e11686fc-4a1b-11e6-9322-c3c27b5a74a0.jpg)
Results page:
Says 0 for my score even though I answered the questions. 
![4](https://cloud.githubusercontent.com/assets/19825728/16862945/25a876ea-4a1c-11e6-9c0e-5e7853b4ed03.jpg)

**Comment by bnkerr** [comment]
On the intro page, the image is from PC video. 
![11](https://cloud.githubusercontent.com/assets/19825728/16863701/892283b2-4a23-11e6-8f7f-f05650569178.jpg)

**Comment by bnkerr** [comment]
And the intro page says "Attempt 1" on it.

**Comment by mattsema** [comment]
all addressed
