### ISSUE TITLE
S5 A3 What Regard for Child Perspectives Looks Like

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#150]
Lesson Objectives:
Replace PC with RCP in paragraph text and lists 
Replace video screenshot to be of RCP
![5](https://cloud.githubusercontent.com/assets/19825728/16862982/7593c178-4a1c-11e6-9040-d4d4dbdb7924.jpg)
Part 1:
Has PC video.
![6](https://cloud.githubusercontent.com/assets/19825728/16863037/ee54c4f4-4a1c-11e6-9088-fd00285847b6.jpg)
Part 2:
Has PC in directions and side panel
Has no video
![7](https://cloud.githubusercontent.com/assets/19825728/16863051/f99e265c-4a1c-11e6-80a4-7f879d73f32a.jpg)
Part 3:
Has PC video
![8](https://cloud.githubusercontent.com/assets/19825728/16863058/0f66ef82-4a1d-11e6-9961-fecf74c1be57.jpg)
Skips from part 3 to part 5
Part 5:
No video
PC in directions (some) and side panel
![9](https://cloud.githubusercontent.com/assets/19825728/16863082/4d38830c-4a1d-11e6-84bf-9eaf17bcc302.jpg)
Feedback is missing
Button tells me my answer is incorrect and to try again. When I hit that button it takes me back. Never can get out without using breadcrumbs. 
![10](https://cloud.githubusercontent.com/assets/19825728/16863108/9b83c9d6-4a1d-11e6-9d83-42645e592d38.jpg)

**Comment by mattsema** [comment]
fixed scoring to allow user to move forward

**Comment by castl350** [comment]
I will fix the flow to this. Sarah, these are your responsibilities so please work to get the right videos in with matt and get the feedback in with Allison.

**Comment by castl350** [comment]
i fixed flow, intro image, RCP chart etc....just needs videos and appropriate feedback now

**Comment by sarahlydic** [comment]
all videos on server. feedback written
