### ISSUE TITLE
S5 A4 Let's Observe Together - Regard

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#151]
Should the line on the main page write out Regard for Child Perspectives (instead of just Regard)? YES - PLEASE FIX (APL)

Non consented teacher in the background. 
![11](https://cloud.githubusercontent.com/assets/19825728/16863150/e386486c-4a1d-11e6-8847-d37627741b73.jpg)

**Comment by castl350** [comment]
fixed the title...not sure what to do about non-consented teacher. policy is not to use videos with non-consented anyones in them? Perhaps she goes away? maybe we can crop video down in screenflow? Sarah, can you think about this.

**Comment by sarahlydic** [comment]
cropped video & put on server
