### ISSUE TITLE
S5 A5 How Regard for Child Perspectives Interactions Support Children's Development

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#152]
Objectives pages:
No image

In opening paragraph should be 'classroom' not 'classrooms' - please take off the 's'
Objectives need periods

Part 1:
Much longer delay -- see "inner pusher...." come up before the video
Then the wheel turned for a while before video came up - APL DIDN'T HAVE THIS ISSUE ON IPAD

![12](https://cloud.githubusercontent.com/assets/19825728/16863233/985f8eba-4a1e-11e6-94ae-d96de9527395.jpg)
Results page:
Not sure we should use the "Well done!" Thoughts on what to go here, @ajp9e ?
![13](https://cloud.githubusercontent.com/assets/19825728/16863237/a8cd4580-4a1e-11e6-9369-368a0e8652b1.jpg)

**Comment by mattsema** [comment]
fixed video skin and text appearing before video

can remove well done from all pages during down time

**Comment by mattsema** [comment]
fixed text before video and video skins
can remove well done during down time

**Comment by castl350** [comment]
The intro image and text are fixed...i also did not experience wheel problems at home

**Comment by castl350** [comment]
videos loaded quite fast actually
