### ISSUE TITLE
S5 A6 Intentionally Building Regard for Child Perspectives

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#153]
Again, no picture on the lesson obj. page.
Know is not bolded like it is in previous objectives list and objectives need periods

Part 1:
Small video box and would not play. -APL DID NOT HAVE THIS ISSUE ON IPAD
![14](https://cloud.githubusercontent.com/assets/19825728/16863277/f13bb2e8-4a1e-11e6-9a0d-e0cf638217fe.jpg)

Well done on summary page again. Might need to change here after decision is made. APL DID NOT SEE THIS ON IPAD

**Comment by mattsema** [comment]
fixed video

**Comment by castl350** [comment]
all content and images fixed and added. video was the right size for me and played quickly. I am on chrome on mac
