### ISSUE TITLE
S5 Discussion: Considering Regard for Child Perspectives

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#156]
Reword to...

It’s important that you take toddlers’ interests, motivation, and points of view seriously. It's also important that you provide spaces where they can develop independence and take responsibility. Think about a time this week when you created this opportunity for a child and describe what happened.

Also is it possible to just have text box for responding versus all of the other options (i.e., attachments, etc)

**Comment by mattsema** [comment]
options included while user posts to discussion can not be removed

**Comment by castl350** [comment]
updated text
