### ISSUE TITLE
S5 TYK

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#157]
Intro page to TYK does not look like sessions 1 and 2 

Qu #3 capitalize Promoting Children's Interests
Qu #4 capitalize Showing Flexibility
Qu #5 capitalize Supporting Children's Independence
Qu #6, 7, 9 capitalize Regard for Child Perspectives
Qu #8 Take out the: True or False at the beginning of the question

#11 Helping children master routines independently works best if you just use one strategy and only one strategy.

Should say...
Helping children master routines independently works best if you just use one strategy. (Or something else, @ajp9e ?) APL AGREES TO THIS REVISION - PLEASE CHANGE 

Qu #12 Please revise item to read:
The teacher says, "Would you like to brush your teeth first or get out your cot first?" change 'you' to 'your'

**Comment by mattsema** [comment]
all fixed
