### ISSUE TITLE
S5 PRACTICE: Applying What You’ve Learned

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#158]
Do the instruction pieces have to be in this format? Looks like a question at first. Same later on. 
![1](https://cloud.githubusercontent.com/assets/19825728/16863552/f0031274-4a21-11e6-9849-25cc5aa7f291.jpg)

Questions 4, 7, and 10 provided correct/incorrect feedback. 
![2](https://cloud.githubusercontent.com/assets/19825728/16863586/4d30ff7e-4a22-11e6-9ee6-2f1ae99a0480.jpg)

**Comment by mattsema** [comment]
the labels are what they must be for the quiz tool

fixed feedback
