### ISSUE TITLE
S6 A3 What Behavior Guidance Looks Like

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#160]
Lesson Obj page:
Says PC in paragraph and bullets
Image of video is from PC

Part 1:
PC video 
Part 2:
PC text and no video 
Part 3:
PC video
No part 4 -- goes from 3 to 5. 
Part 5: 
No video
2nd bullet says BG, but 3rd says PC
PC info in side panel

Feedback page:
Incorrect button, so I'm trapped again (like in S5). Used breadcrumbs to get out. 
![7](https://cloud.githubusercontent.com/assets/19825728/16863822/b1a5c7a8-4a24-11e6-9176-17de6eb00eb3.jpg)

**Comment by mattsema** [comment]
added score of 1 to short answer question to mark answer as correct

**Comment by sarahlydic** [comment]
all videos on server. feedback written
