### ISSUE TITLE
S6 A6 Intentionally Building Behavior Guidance

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#162]
lesson obj page:
no image 
Second sentence of paragraph says PC replace with Behavior Guidance
bold Know in the bulleted list

Part 1:
Video box is really small. VIDEO DOES NOT LOAD ON IPAD. WHEEL SPINS AND SPINS BUT NEVER OPENS

Question after Part 1
For incorrect item - A teacher picks up a child ... 
Feedback comes up on the bottom - 'The teacher is sitting on the floor...' - this should NOT appear

For the item "The children play at the water table while the teacher cleans the table." even though it's the right answer its is highlighted in red. In the feedback for this response replace period with exclamation mark after That's right

Questions are really weird. Some have feedback, others don't. Then this...text says "That's right" but has an incorrect on the button. 
![3](https://cloud.githubusercontent.com/assets/19825728/16863915/b4f0146c-4a25-11e6-9f0c-956ed2b38a1f.jpg)

I got trapped because it said all answers were incorrect. Had to breadcrumb out but couldn't finish lesson. 

Part 2 VIDEO DOES NOT LOAD ON IPAD. WHEEL SPINS AND SPINS BUT NEVER OPENS

Interactive question about Part 2 has all items as incorrect when item "The teacher says, "Keep it down! Friends are trying to sleep." is the right answer. Also the correct feedback for this - replace period with exclamation point after That's right

Part 3 VIDEO DOES NOT LOAD ON IPAD. WHEEL SPINS AND SPINS BUT NEVER OPENS

**Comment by mattsema** [comment]
Lesson Objectives - replaced positive climate with behavior guidance

Videos for parts 1-3 are fixed.  All play on iPad at correct size
Part 1 CYK - gave score of 1 to correct answer to mark as correct and allow user to continue
Part 1 CYK - feedback in question was a fourth option entered into the wrong box - put in fourth option and deleted feedback
Part 2 CYK - gave score of 1 to correct answer to mark as correct and allow user to continue

**Comment by castl350** [comment]
images and into text fixed. I think all other issues related to CYKs and videos were addressed, but i did open a new ticket because the video order is not right...part 2 currently has the intro to this lesson etc....
