### ISSUE TITLE
S6 A8 Targeted Strategies: Supporting Children to Manage Their Behavior Lesson

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#163]
Title of this lesson should read:
Targeted Strategies: Supporting Children to Manage their Behavior

Intro page - missing image
Intro page - change you'll to you will be able to:
Bold know

Effectively Using Consequences = no video

Question after Part 1 
Put the word except in all caps EXCEPT
alignment issue for item - "Follow through..." also seems to be too much spacing between items that doesn't typically happen

Correct feedback - replace period with exclamation mark after That's right

Helping Toddlers Control Impulses = no video

Correct feedback for question -  replace period with exclamation mark after That's right

**Comment by castl350** [comment]
closing ticket. all ! and word bolding addressed. Lesson is not finished so we can't add a screenshot image or the videos yet. we're aware of this so closing the ticket to minimize outstanding issues.
