### ISSUE TITLE
S6 PRACTICE: Applying What You’ve Learned

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#165]
Brittany - Same issues I noted in RCP (incorrect on MC practice questions, etc.) 

Allison - same issue I noted previously on intro page - 3rd sentence should start with Your not You

Allison same issues noted within quiz tool:
info box after #1 and #7 - 2nd sentence change to ... consider what you can do to practice ... replace 'the' with 'to' and last sentence put in the word 'will' in between interactions and impact

Info box after #4 - put in the word 'will' in between interactions and impact

**Comment by mattsema** [comment]
fixed
