### ISSUE TITLE
S5 A2 All About RCP

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#167]
Intro page has PC image

Parts 1, 2, 3 videos have UVA/CASTL logo in it

Before the video for Part 1 plays there's an image that just has 1 and 1/2 parts of the RCP boxes and the same sort of image happens before Part 4 video

Interactive question after Part 3 - align off for "While waiting for lunch..." AND in the feedback for incorrect change 'then' to 'the' - ... following the children's lead.

Part 5 there is a giant space between video and Continue button

**Comment by mattsema** [comment]
Removed logos by switching video skin
The image is the generated thumbnail - can not change
Can not fix alignment - product of Moodle's responsive design
Fixed the language in the responses
Removed space
