### ISSUE TITLE
S5 A8 Targeted Strategies: Supporting Children's Independence

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#168]
Intro page - missing image

Change you'll to - you will be able to 
Bold all of the word 'know'

Interactive question:
In the question please put the word except in all caps (EXCEPT)
In the correct feedback please put an exclamation mark after the That's right

**Comment by castl350** [comment]
All changes made except image because lesson is not ready. i'm closing since this is on the radar to include once lesson is done.
