### ISSUE TITLE
CASTL Watermark on BG CD lesson

### ISSUE THREAD

**Issue by castl350** [castl350/Toddler#174]
Matt, fix issues on BG CD lesson with watermarks and code "inner push" popping up before video displays. 
![screen shot 2016-07-22 at 2 13 47 pm](https://cloud.githubusercontent.com/assets/3357288/17066821/c3c1171a-5016-11e6-8751-0ee7d0ca387e.png)

**Comment by mattsema** [comment]
updated skin and removed broken comments about divs
