### ISSUE TITLE
Assess Your Strengths and Challenges

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#177]
First sentence:
add 's' to challenges

2nd paragraph:
add challenges after the second area so that sentence reads ... areas of strengths and areas of challenges ...

**Comment by castl350** [comment]
I don't think grammatically this makes sense? You have areas of challenge..or challenging areas...

I just switched it to: Intentional teachers are very aware of their own strengths and challenges in the classroom. 

This sentences matches the title more consistently and feels less wordy.
