### ISSUE TITLE
Within Assess Your Strengths and Challenges Quiz

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#178]
Under 'Teaching children social skills' 2nd sentence please change to read arrive at solutions (at is missing) also in the quotes capitalize the first words: Both, Can, That's. And for the first example that starts with Both - that sentence needs a period at the end.

Under Supporting children's emotion regulation change the last sentence to: And when children attempt these, teachers acknowledge their effort.

Under Supporting children's independence during challenges - first example in ( ) please put the period inside the quotation marks.

Under Proactive management of behavior in example (e.g., Hands to yourself; look at me." - capitalize the 'h' and add a period

Under Helping children control impulses ... capitalize the word Freeze and all words in Red Light, Green Light and put the comma within the quotes after "Red Light, Green Light,"   Also please put in semicolons in the sentence that starts with Specifically - one after the word voice;  behavior; 

Question #3 please change to: In a paragraph, describe your role as a teacher and the impact you have on the children in your classroom.

Question #4 the word toddlers should not be capitalized

**Comment by castl350** [comment]
matt, you will need to fix these?

**Comment by mattsema** [comment]
all changes made
