### ISSUE TITLE
Interactive question after Part 1 Social Development

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#179]
I am not sure how consistent we are trying to be but I believe that after each 'That's right!!' we are putting an exclamation mark. 

For Q#2 I didn't think that we were putting the words: TRUE or FALSE at the beginning of T/F questions. Please take out. Also take out the first 'As' at the beginning of the second sentence and start with Young toddlers tend

Also change to That's right!

And I think that there isn't any way to turn off shuffle for the T/F questions - right?

After Social Development is see, "Your score is 2 (out of 2)." Are we supposed to?

**Comment by castl350** [comment]
fixed or didn't fix all content issues. closing and opening new tickets for score is 2 out of 2
