### ISSUE TITLE
3 Seeing the Domains of Children's Development in Action

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#185]
Do we want the number of Attempts to show.

I see ATTEMPT: 1 on the ipad

Scenario 2 of 5 - Physical Development doesn't line up with its bubble

Also at the end I could see my score - if we're showing this, then please disregard.

**Comment by castl350** [comment]
Scenario 2 of 5 is part of the LMS..can't change that..will leave open for attempts and score showing.
