### ISSUE TITLE
S1 Practice: Capturing What You've Learned

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#193]
Session 1 is missing this ... we want teachers to videotape 1 time either after S1 or after S2 - basically we want them to video one time for both these sessions so I think that adding this here will help this.

The text that for S2 can be used here (once it is revised).

**Comment by castl350** [comment]
I will add it to session 1 but think it is confusing to have it in both sessions...will put this on the agenda for thursday discussion.

**Comment by castl350** [comment]
Actually I will not add it to session 1 right now until we discuss further...
