### ISSUE TITLE
A4 The Teaching Through Interactions Framework (TTIF)

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#196]
Not sure how best to change the objectives ... perhaps:

By the end of this lesson you should be: 

Familiar with ...
Able to identify ...

Screenshot doesn't match the videos that are shown - maybe grab a screenshot from beginning of Part 2

After Part 1- Interactive question That's right! needs an exclamation mark

After Part 2 Interactive question That's right! needs an exclamation mark and Feedback needs to say ...Emotional and Behavioral Support (add -al to behavior)

After Part 3 there is not a continue button so I can't get past on the ipad as a student. However when I'm on my desktop as myself I can preview parts 4 and 5 which are linked with right buttons so Part 3 just needs a continue button.

**Comment by castl350** [comment]
fixed all except video issue. The part 3 problem is related to a video not sizing properly...so i'll notify matt..i will close this ticket and open a new one
