### ISSUE TITLE
Activity: Assess Your Own Strengths and Challenges

### ISSUE THREAD

**Issue by mattsema** [castl350/Toddler#2]
Question is not required

**Comment by mattsema** [comment]
Also, do we want/have an icon for questionnaires to go in the intro text?

**Comment by castl350** [comment]
yes, this needs some work but we're waiting for the finalized version.

**Comment by mattsema** [comment]
assessment updated with latest questions

**Comment by sarahlydic** [comment]
can we limit learner to only having submit button instead of both save & submit?

**Comment by castl350** [comment]
removed save button
