### ISSUE TITLE
Intro: Meet the Faces... and Meet Support Team pages

### ISSUE THREAD

**Issue by bds2p** [castl350/Toddler#215]
1.  All titles after names (i.e., Ph.D. and M.Ed.) should have periods following the last letter - they currently do not for Jennifer, Allison, or me.  
2. It's confusing to me that Allison is on both pages, but maybe that's something that was decided before.  
3. For both Allison and my descriptions on the "Meet Your Support Team" page, the first sentence should be changed to, "... is one of two coaches who support..."
4.  In Matt's description, "videotaping assignment" should be plural (i.e., assignments).

**Comment by sarahlydic** [comment]
fixed
