### ISSUE TITLE
Intro: Assess Strengths and Challenges

### ISSUE THREAD

**Issue by bds2p** [castl350/Toddler#216]
In first text box...
 - #1 should be changed to "This is an area **in** which..."
 - #2 needs comma added before "but" (i.e., ...struggle, but...)
 - #4 needs comma added before "but" and delete "with" at the end so it just says "...most of the time, but occasionally struggle."
 
Likert items
 - Can we make the heading of each item bold so it looks separate from its description?
 - First item, first sentence: should be "...especially children **who** may be..."
 - Forth item, last sentence: delete extra period at end 

Items #2 and #3 are the same.  According to Allison's list of items, the first one should be:
"What are your goals and hopes for the coaching process?"

**Comment by sarahlydic** [comment]
fixed. (side note: headings are already bold -- just doesn't show well.)
