### ISSUE TITLE
Home page check boxes

### ISSUE THREAD

**Issue by bds2p** [castl350/Toddler#222]
The check boxes on my home page don't seem to be reflecting what I've completed (see screenshot).  In this case, I completed all of Session 1.2 (A-F), but only F shows that I did it.  I even watched the entire videos for parts A and B, but that didn't make a difference.  Maybe this is an old issue that I just don't know about?  
![screen shot 2016-08-18 at 1 50 22 pm](https://cloud.githubusercontent.com/assets/19825725/17784685/5f300884-654b-11e6-89db-eb737d1b8801.png)

**Comment by sarahlydic** [comment]
this is because of account privileges -- checks do check off for students.
