### ISSUE TITLE
S3 PC TYK Qu #4

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#226]
Which is the best example of a teacher communicating positively with a child?
Select one:
a. The teacher tells a child, “Use your kindness words.”
b. The teacher nods when a child correctly identifies a color during circle time.
c. The teacher responds quickly to children’s needs and works to solve their problem.
d. The teacher asks the child about her weekend and seems genuinely interested in what the child did with her mother.

NONE of these reflect communicating positively with a child ... 

Please change d. to read
d. The teacher smiles and laughs as a child tell her about her weekend.

**Comment by sarahlydic** [comment]
fixed
