### ISSUE TITLE
Session 1.3 video scenarios 2, 3, 4, and 5

### ISSUE THREAD

**Issue by bds2p** [castl350/Toddler#239]
Image for each video shows, but when I press play I get an error message (see screenshot).  The first scenario video works fine.  

![screen shot 2016-08-19 at 1 32 58 pm](https://cloud.githubusercontent.com/assets/19825725/17820699/15b43c26-661c-11e6-94e7-7d5dea6f49b1.png)

**Comment by sarahlydic** [comment]
videos play on chrome on mac and on mobile. error due to internet connectivity.
