### ISSUE TITLE
Session 1 Wrap

### ISSUE THREAD

**Issue by bds2p** [castl350/Toddler#241]
1.  Children's Development, 2nd bullet: "Social" is capitalized, but other domains are not.  I say capitalize all since they are capitalized in most other places throughout.  

2.  Self-Regulation, 2nd bullet: Change dash to a colon to be consistent with the same type of list above it.  

3.  The Nature of Children's Development, 1st bullet: Capitalize Social Development for consistency.

**Comment by sarahlydic** [comment]
fixed
