### ISSUE TITLE
Session 2 Activity 4

### ISSUE THREAD

**Issue by castl350** [castl350/Toddler#37]
On the short answer question, the page keeps going back to itself when you put in any answer. not sure if the settings are off?
![screen shot 2016-06-07 at 11 23 53 am](https://cloud.githubusercontent.com/assets/3357288/15863803/7823e090-2ca2-11e6-9405-7924b0aaba4a.png)
![screen shot 2016-06-07 at 11 24 05 am](https://cloud.githubusercontent.com/assets/3357288/15863806/7951b906-2ca2-11e6-9568-56eb942afe33.png)

**Comment by sarahlydic** [comment]
Had to check the "use regular expressions" box. Now working.
