### ISSUE TITLE
Demo Issue

### ISSUE THREAD

**Issue by castl350** [castl350/Toddler#50]
I found a typo...
![screen shot 2016-06-06 at 2 42 29 pm](https://cloud.githubusercontent.com/assets/3357288/15908482/f40f04ee-2d8f-11e6-96d6-b517492830c6.png)

**Comment by sarahlydic** [comment]
hmm... i'm not seeing the typo?

**Comment by bnkerr** [comment]
That's because Matt is training us right now and it's totally a test! ;) @sarahlydic
