### ISSUE TITLE
S1 TYK - Questions w/ multiple right answers

### ISSUE THREAD

**Issue by sarahlydic** [castl350/Toddler#51]
Just curious. Thought we were staying away from questions with multiple right answers? 
<img width="849" alt="screen shot 2016-06-09 at 7 42 42 am" src="https://cloud.githubusercontent.com/assets/17276503/15928966/15461296-2e18-11e6-9cb6-ed972045b2f3.png">
<img width="845" alt="screen shot 2016-06-09 at 7 43 18 am" src="https://cloud.githubusercontent.com/assets/17276503/15928967/154e8b74-2e18-11e6-893a-06fab3b0e7d2.png">
<img width="848" alt="screen shot 2016-06-09 at 7 57 52 am" src="https://cloud.githubusercontent.com/assets/17276503/15928968/155159da-2e18-11e6-9a99-604566ef090c.png">
<img width="851" alt="screen shot 2016-06-09 at 7 42 23 am" src="https://cloud.githubusercontent.com/assets/17276503/15928970/16e683b0-2e18-11e6-8364-a28a1e104310.png">

**Comment by ajp9e** [comment]
This is not the tyk.

ECI TODDLER PILOT 3 folder - session 1 - TYK - will have a recent date on it.

I previewed it with Matt yesterday and explained that we only have one answer.

In a few minutes I will verify accurate session tyk but it in the pilot 3 folder...

I hope that helps.

A

Sent from my iPad

On Jun 9, 2016, at 8:01 AM, sarahlydic <notifications@github.com<mailto:notifications@github.com>> wrote:


Just curious. Thought we were staying away from questions with multiple right answers?
[screen shot 2016-06-09 at 7 42 42 am]<https://cloud.githubusercontent.com/assets/17276503/15928966/15461296-2e18-11e6-9cb6-ed972045b2f3.png>
[screen shot 2016-06-09 at 7 43 18 am]<https://cloud.githubusercontent.com/assets/17276503/15928967/154e8b74-2e18-11e6-893a-06fab3b0e7d2.png>
[screen shot 2016-06-09 at 7 57 52 am]<https://cloud.githubusercontent.com/assets/17276503/15928968/155159da-2e18-11e6-9a99-604566ef090c.png>
[screen shot 2016-06-09 at 7 42 23 am]<https://cloud.githubusercontent.com/assets/17276503/15928970/16e683b0-2e18-11e6-8364-a28a1e104310.png>

**Comment by ajp9e** [comment]
Hi,

In the most recent tyk the answers are bonded so you all know which one is right. They will to be involved before they go in.

Sent from my iPad

On Jun 9, 2016, at 8:01 AM, sarahlydic <notifications@github.com<mailto:notifications@github.com>> wrote:


Just curious. Thought we were staying away from questions with multiple right answers?
[screen shot 2016-06-09 at 7 42 42 am]<https://cloud.githubusercontent.com/assets/17276503/15928966/15461296-2e18-11e6-9cb6-ed972045b2f3.png>
[screen shot 2016-06-09 at 7 43 18 am]<https://cloud.githubusercontent.com/assets/17276503/15928967/154e8b74-2e18-11e6-893a-06fab3b0e7d2.png>
[screen shot 2016-06-09 at 7 57 52 am]<https://cloud.githubusercontent.com/assets/17276503/15928968/155159da-2e18-11e6-9a99-604566ef090c.png>
[screen shot 2016-06-09 at 7 42 23 am]<https://cloud.githubusercontent.com/assets/17276503/15928970/16e683b0-2e18-11e6-8364-a28a1e104310.png>

**Comment by sarahlydic** [comment]
so sorry! was viewing the wrong tyk...
