### ISSUE TITLE
TYK - Attempt information viewable

### ISSUE THREAD

**Issue by sarahlydic** [castl350/Toddler#54]
I viewed the TYK in the student role & it shows attempt information. Any way to hide this & get learners to the questions with a button like "Start" instead of current?

<img width="797" alt="screen shot 2016-06-09 at 7 40 57 am" src="https://cloud.githubusercontent.com/assets/17276503/15929588/db6350a8-2e1b-11e6-9921-0e49fa945351.png">

**Comment by castl350** [comment]
The student sees the following before starting the quiz tool for the first time (attached).  The above image is what is shown if a user leaves the quiz before submitting and finishing.
![screen shot 2016-06-09 at 8 57 00 am](https://cloud.githubusercontent.com/assets/3357288/15930351/735dc20e-2e20-11e6-8d06-829221db8649.png)
