### ISSUE TITLE
TYK - Final grade not yet graded message

### ISSUE THREAD

**Issue by sarahlydic** [castl350/Toddler#55]
Any way to hide this message? Since I only get 1 attempt and already got my score, it's confusing to see the message "final grade not yet graded."

<img width="722" alt="screen shot 2016-06-09 at 8 28 25 am" src="https://cloud.githubusercontent.com/assets/17276503/15929663/5657857c-2e1c-11e6-8762-74b89f834638.png">

**Comment by sarahlydic** [comment]
NB: This was only for S1 TYK. Didn't appear for S2 TYK.

**Comment by castl350** [comment]
I was able to recreate this with the admin account and switching roles.  However, this message did not appear when testing with the cast_student account.
