### ISSUE TITLE
My Courses - Opening Page

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#56]
The first sentence of this page reads, "This course explores the importance of the teacher's role in the early years of life."

We have the word 'course' everywhere which I am sure can't be helped but I am noting it. 

Also the sentence seems funny to me ... who's early years of life. Perhaps revise to, "This course explores the important of the teacher's role in children's early years of life."

**Comment by bnkerr** [comment]
Agreed. I thought something didn't seem right also. I like the suggested revision.

**Comment by castl350** [comment]
i fixed the course word..i will leave the sentence as is as i think the edit is too wordy.
