### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#57]
At the top it reads "Course Introduction" again here I am with the 'course' business again ... can we just have 'Introduction'?

Also the paragraph reads, 'This course ...' maybe instead 'This online experience ...' or 'ECI Toddler' and there's that weird sentence again ... perhaps consider changing to, "importance of the teacher's role in children's early years of life.'

**Comment by castl350** [comment]
I fixed and took out word. I don't think the sentence is weird..I think the those is implied and this comes directly off the old toddler course (oops :).
