### ISSUE TITLE
Transition from Your Role and Responsibilities back to home page

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#61]
Hi,
So at the end of Your Role and Responsibilities, there's a button that takes you back to the home page. Will a learner then just figure out what they should do next? Maybe the button should go to 'Assess Your Own Strengths and Challenges'? I'm not sure ... just wondering. Thanks

**Comment by castl350** [comment]
We could send it to the assess your strengths and challenges..but note that we cannot send the assess to the discussion...

**Comment by castl350** [comment]
i'm not sure we should send them there on second thought..ther his a clear demarcation in the LMS between these 4 intro pages and then the two activities: assess and discussion...i would feel like i would want to return learners to the LMS
