### ISSUE TITLE
Assess Your Own Strengths and Challenges

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#62]
#1 We need to revise this text more and I have put it on our radar to do so ... 

#2 I am wondering about the button (that's not there) - will it be like the others - in a box that reads Answer the Questions (I think that the word questions should capitalized)

#3 After you submit questionnaire it goes to a page that says, 'Your response' - I think that the word response needs to be capitalized AND I am not sure what I do next as a learner once I have looked at my responses. How do I get out of here? I touched the word 'Course Introduction' at the top of the page and it didn't take me anywhere ... When I touch the word 'Assess Your Own Strengths and Challenges' at the top of the page it takes me to the initial paragraph and it reads, "You have already filled out this questionnaire for us. Thank you." Under that it reads. "Your response" which then takes me back to my responses and I am stuck again.

I got out by tapping ECI: Toddler (V3) at the top of the page to return to the home page. Is that something that teachers will intuitively know to do?

**Comment by bnkerr** [comment]
The ranking scale currently says the following for 3: Area of strength and growth. Sometimes I do very well in this area. Other times it is more of struggle. 

Should end with, "Other times it is more of a struggle." (Add in the word a.)

And I experienced the same thing trying to figure out what's next after completing the questionnaire. Can we get a continue button put in?

**Comment by mattsema** [comment]
questionnaires can not be linked to a next activity
fixed wording in scale

**Comment by mattsema** [comment]
changing the styling of this link to a button would be difficult given how it is created.  I can explore later if we want to pursue this.
