### ISSUE TITLE
Discussion in Before You Start

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#63]
When I tapped 'Reply' I got this:
Sorry, you are note allowed to post to this forum
More information about this error - when I tapped that I got, "Safari cannot open the page because it could not load any data." Then it sent me to the itc page and then when I did the back web page arrow I got to an LMS page that read Enrollmet options
I was able to get out by tapping My Courses to get back to the home page.

Perhaps the discussion boards are not set up yet ...

**Comment by bnkerr** [comment]
I also received the "Sorry, you are not allowed..." error as well for the DB.

**Comment by castl350** [comment]
Matt, can you check settings on discussion..maybe this wasn't done before testing?

**Comment by mattsema** [comment]
Course setting needed to be changed to allow students to not only view but respond to posted question in dicussion

Fixed.
