### ISSUE TITLE
Bolding in the Introductions and Objectives

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#64]
In The Big Ideas learning objectives words like know, see, reflect... are not bolded but in Sessions 1 and 2 they are ... does this matter? Brittany?

**Comment by bnkerr** [comment]
![s1_intro page](https://cloud.githubusercontent.com/assets/19825728/15995822/be747a0a-30ee-11e6-9c93-8f03881ab7c9.jpg)
![s0_intro page](https://cloud.githubusercontent.com/assets/19825728/15995821/be737218-30ee-11e6-87b5-60f2eda16167.jpg)

So for me, I can barely even tell that they're bolded. I think bolding is nice though. @ajp9e

**Comment by castl350** [comment]
The Big Ideas is not a session introduction page...and the words BIG IDEAS cannot be changed in green because it is consistent like that in the LMS. The Two Big Ideas matches up here with the Introductiona nd Objectives title in the session 1 screenshot above...
