### ISSUE TITLE
The Five Domains of Development opening page

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#65]
3rd bullet - the word 'look' needs an 's'

4th bullet - the word domain has an 's' and it shouldn't

**Comment by bnkerr** [comment]
This one has...

By the end of these lessons, you'll:

All of the others say, "....end..., you should be able to:"

**Comment by bnkerr** [comment]
Scratch what I said above... :) :) :)

**Comment by castl350** [comment]
i fixed all of that except i changed the 4th bullet entirely because it is supposed to focus on skills interconnecting within and across domains...and that was not coming across in the current bullet...
