### ISSUE TITLE
S1 A2 A. Social Development interactive qus after lesson

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#66]
The feedback for the first interactive question after the lesson is redundant - the information in green (the correct choice) is exactly the same as the feedback. Do we need to have feedback here? 

For the second question, true/false - the first time I did it choices were False, True - the next time I did it the choices were True/False so I am wondering is the shuffle feature for this item is on? 

For true/false questions what is the protocol? For this one, when I choose the false (the wrong answer) it reads:
Your answer: False
Incorrect. Please try again.

I am wondering if for true/false questions like this they don't try again? And instead the page reads:
Your answer: False
Incorrect. The correct answer is True. (insert statement that is true) 
OR is this too big of a pain and it's just easier to do it this way? 
Just wondering ...

**Comment by castl350** [comment]
unfortunately moodle shuffles and there is not a way to change that....so this has always been the case...I think it would be strange that for all other questions you try again, and for T/F you would not. If you got it wrong, it would not hurt for you to re-read the question and try again? I'll fix the feedback but know that these were pulled from the original course...
