### ISSUE TITLE
S1 A2 B. Emotional Development Interactive questions

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#68]
#1 What is the domain of Emotional Development?
For Social Development we had the same question except it read, "What is the domain of Social Development all about?" Physical Development is also worded this way.
I think that we should add 'all about' to the end of this question.

Also the buttons are not aligned. I can't take a screenshot and send to you b/c I am testing on the ipad. When I enlarge or shrink the page the buttons are still not aligned.
For the correct feedback - it's redundant as noted for Social Development. If for whatever reason we keep this feedback then the words Emotional Development need to be capitalized in the sentence.

#2 This has good feedback that is not redundant.

**Comment by bnkerr** [comment]
Here's the spacing issue that I see as well. 
![s1 a2b](https://cloud.githubusercontent.com/assets/19825728/15995895/b0819c56-30ef-11e6-84a1-023be90714b7.jpg)

**Comment by castl350** [comment]
fixed feedback and question. nothing to be done on the alignment front
