### ISSUE TITLE
Trying to go back to a lesson

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#69]
So I wanted to go back to confirm what the first interactive question was for social development. I have already done this lesson and I have reviewed it. So from the home page when I clicked on Social Development the page read:
A. Social Development 
You are not allowed to retake this lesson.
Return to the course

I think that this just needs to be changed ... and also the message should be 'Return to home page' right?

**Comment by castl350** [comment]
Matt, can you check this? The flow control settings are set the way they should be so i'm not sure what is happening here?

**Comment by mattsema** [comment]
not allowed to retake message a result of a setting in the grades section.  Fixed for this and settings confirmed for all other lessons
