### ISSUE TITLE
S1 A2 C. Physical Development interactive questions

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#70]
#1 The buttons are not aligned. This might be an ipad thing and not a big deal. When I look online the buttons are aligned and sometimes get misaligned when resizing ... 
Feedback is redundant

#2 Bullets are aligned here
Feedback is helpful and not redundant

**Comment by castl350** [comment]
can't do anything about alignment in bullets..LMS related. updated the feedback for 1
