### ISSUE TITLE
S1 A2 F. Quick Review of the Five Domains

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#72]
First sentence - missing the word 'the' after the word about

Social Development - the all should be capitalized. The first word in each of the others is.
There should be a period after every definition - a period is missing for Emotional Development, Physical Development, Thinking and Learning

**Comment by bnkerr** [comment]
And a comma is needed in the last sentence...

In the next activity, you'll...

**Comment by castl350** [comment]
fixed...gracias
