### ISSUE TITLE
S1 A3 Seeing the Domains of Children's Development in Action

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#73]
Since this activity has been revised the text on the intro page needs to change. Take out the words 'and associated skills'

#1 There is a space before the words 'That's right! so the paragraphs aren't aligned. This doesn't resolve when you resize the page.
#2 Physical Development is not aligned with it's button. This is also true on the desktop. Also 'No source video was found' - and this is also true on the desktop
#3 In the correct feedback for this there is no space between the second and third paragraphs like there is in the first two
#4 No source video found
In the correct feedback all of the information is in one paragraph. To be consistent, there is a space between the first part of information (That's right! Definition) and the second part (In this scenario...)
#5 same issues as above
Also in the correct feedback, the last sentence, what the girl is saying needs a comma - ... she says, "I have an idea," - needs a comma

**Comment by bnkerr** [comment]
![s1 a3 video 2](https://cloud.githubusercontent.com/assets/19825728/16024500/5996548a-3190-11e6-81a3-bf7c1a952956.jpg)
Here's a screenshot of what Allison mentioned in #2. 

Also, we are consistent with spacing on the feedback. Some have the definition then a new line and the scenario. Some start a new paragraph with the scenario. Some are all in one paragraph. (Attaching a shot of each.) I don't care which one we use -- just need to pick one and add it to the style sheet. @ajp9e what do you think it should be? 

![s1a3 - 1](https://cloud.githubusercontent.com/assets/19825728/16024660/04a3b610-3191-11e6-8a73-761eada4b3f9.jpg)
![s1 a3 - 2](https://cloud.githubusercontent.com/assets/19825728/16024661/04b10bb2-3191-11e6-8222-22a5d71e71bc.jpg)
![s1 a3 - 3](https://cloud.githubusercontent.com/assets/19825728/16024662/04b12f34-3191-11e6-83c2-da9e3a02b475.jpg)

**Comment by castl350** [comment]
hi guys, i made the feedback into all one paragraph. For LMS formatting, this was the easiest way to achieve cohesion. I removed the space on the "That's right" piece. There is nothing we can do about the alignment (or off alignment) of the MC choices. the LMS occasionally does this out of our control
