### ISSUE TITLE
S1 A4 The Importance of Self-Regulation

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#74]
First sentence of the intro self regulation needs a hyphen 

First bullet - self regulation needs a hyphen
Second bullet - no 'al' - should be emotion and behavior 
Third bullet - self regulation needs a hyphen
All need a period at the end

#1 interactive question - nice feedback
At the end of this lesson - on the page with the choices to review, continue, return - It says "Your score is 1 (out of 1)."

**Comment by castl350** [comment]
fixed all of the spelling and grammar issues...
Matt will fix that display of score across all the lesson so i'm closing this comment.
