### ISSUE TITLE
S1 A4 Emotion Regulation

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#75]
On the intro page for Emotion Regulation in the first sentence Emotion Regulation is capitalized and then in the bulleted list it's not. I tried to go back to look at self-regulation but I got the message 'You are not allowed to retake this lesson.' I wanted to go back to see whether or not we had capitalized self-regulation in the sentences - I think not. I know the first time it was in double quotation marks. I think that we just need to make a decision and then be consistent throughout. Brittany - your thoughts?

All of the bulleted items need a period at the end

For all of the videos there is an error message, "Error no source video was found," I'm on the ipad but I can play the videos on my desktop. And on the ipad I can see an image of the video but the video doesn't play - just shows error message

**Comment by bnkerr** [comment]
First sentence should be...

In this lesson, we'll focus on Emotion Regulation and see an example of how young children are working to recognize and manage emotions with guidance from their teacher. (without comma after ER)

OR 

In this lesson, we'll focus on Emotion Regulation, and we'll see an example of how young children are working to recognize and manage emotions with guidance from their teacher. (add second we'll)

**Comment by castl350** [comment]
we wil not capitalize it unless it's in the title or the multimedia lesson as a stand alone idea...i have changed all for consistency
