### ISSUE TITLE
S1 A4 Emotion Regulation Interactive Question and last page

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#76]
On the ipad the circles before the items are not aligned - resizing doesn't help.

I can see Your score is 1 (out of 1).

**Comment by castl350** [comment]
Matt, can we make sure to comment out the score. Unfortunately, nothing we can do about the sizing..that is a moodle LMS issue.

**Comment by mattsema** [comment]
score/message with no score will be removed during downtime
