### ISSUE TITLE
S1 A4 Behavior Regulation

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#77]
Same issue with capitalization ... initially it's capitalized and not in double quotes like self-regulation but then not capitalized anywhere else ... 

All bulleted items are missing periods

Similar to Emotion Regulation - I can see image of video in back I get error message - no source video was found - this is true for all parts

At the end of the lesson above the 3 buttons it reads, "Well done!"

**Comment by bnkerr** [comment]
Same error for me....
![video error](https://cloud.githubusercontent.com/assets/19825728/16024903/48fc8926-3192-11e6-94d3-d5906488a9db.jpg)

**Comment by castl350** [comment]
I uncapitalized it in the objectives at the start. It should only be capitalized as a title on the page or in the lesson.
