### ISSUE TITLE
S1 A4 Cognitive Regulation - intro content needed

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#78]
How does this work? Basically just copied from others:
In this lesson, we'll focus on Cognitive Regulation, and consider how young children and adults manage their thoughts.

By the end of this lesson, you should be able to:
Know what cognitive regulation is.
Know how young children are building cognitive regulation.
Know what cognitive regulation looks like in a typical toddler classroom.

**Comment by castl350** [comment]
sounds great. except i don't think we capitalize cognitive regulation unless it's a title on a page or in a  lesson?
