### ISSUE TITLE
S1 A4 Cognitive Regulation - interactive question?

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#79]
Do you think that we need an interactive question?
Self-Regulation has one
Emotion Regulation has one
Behavior Regulation doesn't 
So ...

**Comment by castl350** [comment]
Yes, we need a question for both behavior and cognitive regulation actually..that's why those activities didn't check off as they should..i will put a placeholder in.

**Comment by castl350** [comment]
question added in.
