### ISSUE TITLE
Difference between ipad and desktop

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#80]
At the end of the lesson on the ipad there is one of two messages that pop up that don't pop up on the desktop.

If there is an interactive question then it will give me 'score'  as I have noted in a previous thread.
If there is not an interactive question then it says, "Well done!" at the end.

Just wanted to bring that to your attention in case you didn't know ...

**Comment by castl350** [comment]
hmm..thank you! we have not experienced that..what version o the iPad are you using? one from the project? good to know. Matt, can you confirm?

**Comment by mattsema** [comment]
messages will be removed during down time
