### ISSUE TITLE
S1 Discussion question

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#81]
Same issue as before, perhaps these are not set up yet.

Message - Sorry, you are not allowed to post to this forum.

**Comment by bnkerr** [comment]
Same here. Then it forces me back to the homepage. Want to make sure there is a way to go straight from posting in DB to the Unique lesson.

**Comment by castl350** [comment]
There is not a straight way to go from the discussion to the next activity unfortunately...that is a feature of Canvas, but not of moodle. Matt, can you check on the discussion settings.

**Comment by mattsema** [comment]
discussion settings corrected
