### ISSUE TITLE
S1 TYK - a is the right answer alot & 1 revision

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#83]
Overall the right answer was 'a' for questions - 1, 3, 6, 7, 8 - in the word document I mixed this up a little more (1-d, 3-b, 6-b, 7-a, 8-c). Are these on shuffle or could the LMS be putting the right answer first? 

#4 a - please change 'telling' to tells - thank you

**Comment by castl350** [comment]
Matt, can you fix this?

**Comment by mattsema** [comment]
the questions are shuffled this experience was random

fixed wording for question 4
