### ISSUE TITLE
S1 TYK Feedback

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#84]
Do we want any more feedback than the redundant auto-generated feedback? I think that this is fine just throwing it out there.

**Comment by bnkerr** [comment]
I hear you, @ajp9e. Seems a little redundant, which I think is fine. Just want to be consistent with it...

Seems like the true/false questions don't say, "Your answer is correct/incorrect." See screenshot. 
![s1 tyk](https://cloud.githubusercontent.com/assets/19825728/16025335/caa51612-3194-11e6-900d-2266fecc5017.jpg)

**Comment by castl350** [comment]
That's up to you guys. I believe this is what we were given? If not, can we double-check for additional feedback?

**Comment by mattsema** [comment]
we are using the full extent of the automatic feedback.  Anything more will have to be added per question or question answer

**Comment by castl350** [comment]
I think we're good on this then. I'll close as it sounds like a systematic function of the LMS that would require much more work to individualize.
