### ISSUE TITLE
S1 TYK - once you're finished and where to go

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#85]
So once you finish the TYK you look at the feedback and then you click Finish Review at the bottom which then takes you to a page that looks just like the Intro page but it includes your test score - is that what's supposed to happen? Then you move on by clicking Back to the course at the bottom which then takes you to the home page - not the next thing to do after the TYK - will learners know where to go next?

And maybe this is because we haven't given you the 'next' yet which will be the PLAN: Plan Your Taping for session 1 :)

**Comment by castl350** [comment]
You can't create a NEXT from a TYK unfortunately. I'll have Matt double-check but I do think his is what happens....same thing with the discussion questions. may be confusing it with the functionality of Canvas which does include a next and back on all formats, including quiz and discussions)

**Comment by mattsema** [comment]
quizzes, questionnaires, and discussions can not have a link to next activity in moodle
