### ISSUE TITLE
S2 A2 Your Everyday Interactions Matter

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#86]
On the ipad for Part 1 the error message is 'no soucre video was found' but on my laptop the video loads and plays 
Part 2 - serve and return video about brain circuitry PLAYS
Part 3 - error message on ipad but plays on laptop
Interactive question - on the ipad there is a space between choices 3 and 4 that doesn't go away when resized and the 4th bubble is not aligned with the rest - again resizing doesn't change this 
Another interactive question issue - the 'right' answer works - when you chose it, it gives feedback but when you choose the wrong answer it goes to the Part 4 video (on the laptop it just goes back to the question for you to chose again)
Part 4 - on the ipad error message, but on laptop loads and plays
Part 5 - Tronick video plays on the ipad
Part 6 - ipad error message, video doesn't play, on laptop video plays
And on the last page when you click the 'Review This Lesson' it takes you to the intro page and starts the lesson again as opposed to the review way. I know this because when you typically review, if you get the interactive right the bubble next to it is very small and it wasn't

**Comment by bnkerr** [comment]
Spacing is off a bit...
![s2 a2 question spacing](https://cloud.githubusercontent.com/assets/19825728/16028984/e66f37e2-31b2-11e6-8d0a-ce0d997a5760.jpg)

**Comment by bnkerr** [comment]
When I select any wrong options in the question posted above, it takes me straight to the next video without telling me correct/incorrect. If I select the correct, I get correct notification and feedback.

**Comment by bnkerr** [comment]
For part 4, I got the wheel of death for well over 30 seconds. Then I got this:

![s2 a2 part 4](https://cloud.githubusercontent.com/assets/19825728/16029041/7aba729a-31b3-11e6-8c2b-8f3cf4931302.jpg)

**Comment by bnkerr** [comment]
For the final page of this activity, it tells me my score is 0. I don't know how that is the case when the question is the type that tells me to try again until I get it right. 
![s2a2 final page](https://cloud.githubusercontent.com/assets/19825728/16029079/d9105472-31b3-11e6-8614-66141661c908.jpg)

**Comment by castl350** [comment]
I fixed the flow of this lesson so that it allows for learners to try questions multiple times. Matt, can we check on the videos, and also make sure that the Your score is 0 (out of 1) is something that doesn't show up for learners..it's not showing up in my view but could just be a student view thing? let's comment out.

**Comment by mattsema** [comment]
message will be removed during down time
videos are fixed
