### ISSUE TITLE
S2 A4 Part 4

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#91]
Video - No source video was found, on the laptop this video loads and plays

I can submit my answer just fine ... 

Feedback for Part - RCP 2nd bullet doesn't need a comma

**Comment by castl350** [comment]
Matt, can you troubleshoot video on the iPad....

**Comment by castl350** [comment]
Comma has been removed on feedback.

**Comment by mattsema** [comment]
video converted for use on ipad

fixed
