### ISSUE TITLE
S2 A5 Your Turn

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#93]
The intro page for this needs to be changed to take out the second objective - learners are just identifying which dimension now ... not which area 
#1 This question can be annoying because you have to keep doing until you have all 4 correct ... in the feedback the information is missing for each dimension - looks like this:
Behavior Guidance -
Positive Climate -
Teacher Sensitivity - 
Regard for Child Perspectives - 
I'm happy to provide the definition for each one ... or just take out the hyphen
For the 4th video (washing hands example) in the feedback the dimension (Regard for Child Perspectives) is capitalized but in the feedback for Positive Climate and Teacher Sensitivity this isn't the case. I think that we should just be consistent and I like not capitalizing. So then feedback should go like this:
That's right. The teacher is being sensitive by checking in on a child. (KEEP)
That's right. The teacher is creating a positive climate as she and the children play together. (KEEP)
That's right. The teacher shows regard for the children by letting them wash their hands and move to the table. (CHANGE)

After this question then I am stuck in a loop - it just goes back to this RCP question and I cannot get out.

**Comment by bnkerr** [comment]
Same loop thing happened to me.

**Comment by castl350** [comment]
I adapted the objectives and intro

**Comment by castl350** [comment]
Question 1 is from the previous course and can be taken out or can stay...that is a content call.

**Comment by castl350** [comment]
I uncapitalized RCP and changed the language slightly...PC was not capitalized....

**Comment by castl350** [comment]
I made sure that RCP question jumps to the next page

**Comment by castl350** [comment]
The definition for each of the dimensions on question 1 would be great. Thanks for providing those allison. will leave this ticket open. otherwise all items are caught.

**Comment by castl350** [comment]
Since we have a CYK that asks learners to identify the 4 dimensions, I will scrap question 1 in this interactive. I agree that it would be lesson confusing and makes more sense.
