### ISSUE TITLE
S2 A6 Becoming a Better Observer 

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#94]
Part 3 - no source video was found error; bu on the laptop the video loads and plays
Part 4 - video for learners to watch error message on ipad but on the laptop loads and plays
Part 5 - ipda no source video was found error

At the end of lesson, review this lesson just starts lesson over

**Comment by bnkerr** [comment]
Place a : after "here's a list:"

Then in the last line the . should come before the '

**Comment by bnkerr** [comment]
^^^^ on the feedback page that says to compare your answers to ours.

**Comment by bnkerr** [comment]
There's no Part 4 of 5 subtitle.

**Comment by bnkerr** [comment]
Lesson started over for me too.

**Comment by castl350** [comment]
The lesson is supposed to start over. That's what the "review this lesson" button has always done. :)

**Comment by castl350** [comment]
I fixed the colon and the period in the feedback. I believe the capitalization on the Compare your answers to ours is left lower-case on purpose because the Your answer is also the same and that is done by the LMS. So i would not capitalize to be consistent.

**Comment by castl350** [comment]
Added Part 4 of 5. Quiz questions don't include the title for some reason so it has to be added manually. good catch

**Comment by castl350** [comment]
Only thing left to do on this one is compare videos from iPad to computer

**Comment by ajp9e** [comment]
In session 1 when you review a lesson there is a difference when reviewing that I noted in session 2. For example, and I noted this in session 1, when you review a lesson, the interactive question is already answered as the button is smaller than the others. Also if you have completed anything within the lesson, like type in an answer, you can't do it again. 

Perhaps in a lesson that has neither an interactive question or activity then it simply does the lesson again.

**Comment by mattsema** [comment]
videos fixed
