### ISSUE TITLE
Intro pages 

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#99]
S0 intro page should have a sub title as well (the text in teal)? Or not? S0 is different visually than the others. 

![s0_intro page](https://cloud.githubusercontent.com/assets/19825728/15995763/2846c286-30ee-11e6-8ed1-84db9b5f14e4.jpg)
![s1_intro page](https://cloud.githubusercontent.com/assets/19825728/15995764/2a61bbac-30ee-11e6-8491-fcb394f6d3ce.jpg)

**Comment by bnkerr** [comment]
Also, for this...should we have for S0...

By the end of these modules (or whatever), you should:
.....

**Comment by castl350** [comment]
No, this is not intended to be a module..simply information that precedes starting the session..I'm happy to put teal on the title, but it does not need objectives.

**Comment by castl350** [comment]
Actually, I can't put teal on the Two Big Ideas since that title is styled by the LMS itself....It is fine as is..hope that helps..
